prac/urls.py
from django.urls import path
from prac.views import (HomeTemplateView, 
                        IndividualView, 
                        CarCreateView, 
                        CarUpdateView, 
                        CarDetailView,
                        CarDeleteView,
                        OtherCarOwner)

app_name = 'prac'

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('individual/', IndividualView.as_view(), name='individual'),
    path('<int:pk>/other/', OtherCarOwner.as_view(), name='other'),
    path('create/', CarCreateView.as_view(), name='create'),
    path('<int:pk>/detail/', CarDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', CarUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', CarDeleteView.as_view(), name='delete'),
    
]

practice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('prac.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

prac/models.py
from django.db import models
from django.contrib.auth.models import User


class Car(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    year = models.DateField()
    
    
    def __str__(self):
        return self.owner.first_name

accounts/views.py
from django.shortcuts import render

# Create your views here.

prac/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.contrib.auth.mixins import (LoginRequiredMixin, 
                                        UserPassesTestMixin)
from django.views.generic import (TemplateView, 
                                  CreateView, 
                                  UpdateView, 
                                  DetailView, 
                                  DeleteView)
from prac.models import Car

class HomeTemplateView(TemplateView):
    
    model = Car
    template_name = 'prac/home.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["car"] = Car.objects.all()
        return context
    
    
class IndividualView(TemplateView):
    model = Car
    template_name = 'prac/individual.html'
    
    def get(self, request, *args, **kwargs):
        context = Car.objects.filter(owner=self.request.user)
        return render(request, self.template_name, {'context':context})
    
class OtherCarOwner(TemplateView):
    model = Car
    template_name = 'prac/other.html'
    
    def get(self, request, *args, **kwargs):
        context = Car.objects.filter(owner=self.request.user.username)
        return render(request, self.template_name, {'context':context})
    
class CarCreateView(LoginRequiredMixin, CreateView):
    model = Car
    template_name = 'prac/create.html'
    fields = ['name', 'brand', 'model', 'year']
    success_url = '/'
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(CarCreateView, self).form_valid(form)
    
    
class CarDetailView(DetailView):
    model = Car
    template_name = 'prac/detail.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
    
class CarUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Car
    template_name = 'prac/update.html'
    fields = ['name', 'brand', 'model', 'year']
    success_url = '/'
    
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.owner:
            return True
        return False
    

class CarDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Car
    template_name = "prac/delete.html"
    
    def get_object(self):
        pk_ = self.kwargs.get("pk")
        return get_object_or_404(Car, pk=pk_)
    
    def get_success_url(self):
        return reverse("prac:home")
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.owner:
            return True
        return False
            
    

prac/templates/prac/create.html
{% block content%}
<form method="POST">
{% csrf_token %}
{{ form.as_p}}
<button type="submit">Submit</button>
</form>
{% endblock %}

prac/templates/prac/delete.html
{% block content %}
<form method="POST">
    {% csrf_token %}
    <h5>Would you like to delete this object.</h5>
    <button type="submit">Delete</button>
</form>
{% endblock %}

prac/templates/prac/detail.html
{% block content%}
<form method="POST">
    {% csrf_token  %}
<h1>{{object.owner}}</h1>
<h1>{{object.name}}</h1>
<h1>{{object.brand}}</h1>
<h1>{{object.model}}</h1>
<h1>{{object.year}}</h1>
<a href="{% url 'prac:delete' object.pk %}"><h1>Delete?</h1></a>
<a href="{% url 'prac:update' object.pk %}"><h1>Update?</h1></a>
</form>
{% endblock %}

prac/templates/prac/home.html
{% for item in car%}
<a href="{% url 'prac:other' item.pk %}"><h1>{{item.owner}}</h1></a>
<a href="{% url 'prac:detail' item.pk %}"><h1></h1>{{item.name}}</h1></a>
<h1>{{item.brand}}</h1>
<h1>{{item.model}}</h1>
<h1>{{item.year}}</h1>
{% endfor%}

prac/templates/prac/individual.html
{% for item in context%}

<h1>{{item.owner}}</h1>
<h1>{{item.name}}</h1>
<h1>{{item.brand}}</h1>
<h1>{{item.model}}</h1>
<h1>{{item.year}}</h1>
{% endfor%}

prac/templates/prac/other.html
{% for item in context%}

<h1>{{item.owner}}</h1>
<h1>{{item.name}}</h1>
<h1>{{item.brand}}</h1>
<h1>{{item.model}}</h1>
<h1>{{item.year}}</h1>
{% endfor%}

prac/templates/prac/update.html
{% block content%}
<form method="POST">
{% csrf_token %}
{{ form.as_p}}
<button type="submit">Submit</button>
</form>
{% endblock %}